-- Kratka imena slovaških klubov: kraj namesto začetnic.
--
-- Uvoz je kratko ime sestavil iz začetnic uradnega imena: "TJJB" (Telovýchovná
-- jednota JEDNOTA Bánová), "ŠBOZ" (ŠK Badín, občianske združenie), FK Terchová
-- in FK Turie pa sta bila oba "FT". Rezultati in naslovi tekem kažejo samo
-- kratko ime. Novo pravilo je `kratkoImeSk` v scripts/viri/sportnet.mjs (za
-- nove klube); obstoječe popravimo tu. Po imenu, ker je ime unikatno znotraj
-- države (id-ji se med bazami razlikujejo).
--
-- Obenem vrstni red skupin VI. lige SsFZ: bil je B, A, D, C.

update public.teams t
   set short_name = v.kratko
  from (values
  ('ŠK Badín, občianske združenie', 'Badín'),
  ('OŠK Rosina', 'Rosina'),
  ('Futbalový klub Čadca', 'Čadca'),
  ('TJ Sokol Zubrohlava', 'Zubrohlava'),
  ('FK Slávia Staškov', 'Slávia Staškov'),
  ('TJ PARTIZÁN OSRBLIE', 'Osrblie'),
  ('OŠK BEŠEŇOVÁ', 'Bešeňová'),
  ('OŠK Baník Stráňavy', 'Stráňavy'),
  ('TJ Sokol Medzibrod', 'Medzibrod'),
  ('TJ Tatran Krásno nad Kysucou', 'Krásno'),
  ('TJ Spartak Radôstka', 'Radôstka'),
  ('FK FILJO LADOMERSKÁ VIESKA', 'Ladomerská Vieska'),
  ('ŠK Javorník Makov', 'Javorník Makov'),
  ('ŠK Prameň Kováčová', 'Kováčová'),
  ('"TJD Príbelce"', 'Príbelce'),
  ('MFK Bytča', 'Bytča'),
  ('MŠK Kysucké Nové Mesto', 'Nové Mesto'),
  ('TJ Tatran Oravské Veselé', 'Oravské Veselé'),
  ('Telovýchovná jednota JEDNOTA Bánová', 'Bánová'),
  ('TJ Višňové', 'Višňové'),
  ('FK Tatran Turzovka', 'Turzovka'),
  ('MFK Nová Baňa', 'Nová Baňa'),
  ('FK BREZNO', 'Brezno'),
  ('TJ Dlhé Pole', 'Dlhé Pole'),
  ('TJ Divina', 'Divina'),
  ('OFK Hôrky', 'Hôrky'),
  ('Telovýchovná jednota TATRAN Bytčica', 'Bytčica'),
  ('FK Strečno', 'Strečno'),
  ('TJ Hlboké', 'Hlboké'),
  ('FK Terchová', 'Terchová'),
  ('FK Turie', 'Turie'),
  ('OŠK Divinka - Lalinok', 'Divinka Lalinok'),
  ('OFK Kotešová', 'Kotešová'),
  ('TJ ŠTART Veľké Rovné', 'Veľké Rovné'),
  ('FK Rajec', 'Rajec'),
  ('TJ Stráža', 'Stráža'),
  ('FK Zástranie', 'Zástranie'),
  ('ŠK Štiavnik', 'Štiavnik'),
  ('ŠK Cementáreň Lietavská Lúčka', 'Lietavská Lúčka'),
  ('TJ Považský Chlmec', 'Považský Chlmec'),
  ('FK Ďurčiná', 'Ďurčiná'),
  ('FK FATRAN - Dolná Tižina', 'Dolná Tižina'),
  ('TJ Kolárovice', 'Kolárovice'),
  ('TJ Partizán Súľov', 'Súľov'),
  ('TJ Družstevník Hričovské Podhradie', 'Hričovské Podhradie'),
  ('Športový klub Dynamo Kotrčina Lúčka', 'Kotrčina Lúčka'),
  ('Telovýchovná jednota JEDNOTA Bánová B', 'Bánová B'),
  ('TJ Rozvoj Mojš', 'Mojš'),
  ('TJ Hvozdnica', 'Hvozdnica'),
  ('TJ Tatran Hrabové', 'Hrabové'),
  ('TJ Pšurnovice', 'Pšurnovice'),
  ('FK Hliník', 'Hliník'),
  ('TJ POVAŽAN Nezbudská Lúčka', 'Nezbudská Lúčka'),
  ('Družstevník Rašov', 'Rašov'),
  ('OFK Ovčiarsko', 'Ovčiarsko'),
  ('TJ Fatran Krasňany', 'Krasňany'),
  ('FK Trnové', 'Trnové'),
  ('TJ Jablonové', 'Jablonové'),
  ('TJ Hviezda Zádubnie', 'Zádubnie'),
  ('ŠK Dolný Hričov', 'Dolný Hričov'),
  ('TJ ŠK Podhorie', 'Podhorie'),
  ('ŠK Petrovice', 'Petrovice'),
  ('RTJ Brodno', 'RTJ Brodno'),
  ('ŠK Lietava', 'Lietava'),
  ('AC UNIZA', 'AC Uniza'),
  ('ŠK Tvrdošín', 'Tvrdošín'),
  ('ŠK Dynamo Diviaky', 'Diviaky'),
  ('FC Sedem Námestovo', 'Sedem Námestovo'),
  ('OŠK Švošov', 'Švošov'),
  ('ŠK Závažná Poruba', 'Závažná Poruba'),
  ('ŠK Čierne', 'Čierne'),
  ('ŠK Belá', 'Belá'),
  ('Oravan Oravská Jasenica', 'Oravská Jasenica'),
  ('OFK Teplička nad Váhom', 'Teplička'),
  ('FK Predmier', 'Predmier'),
  ('FC 34 Liptovský Mikuláš - Palúdzka', 'Mikuláš Palúdzka'),
  ('TJ Družstevník Liptovská Štiavnica', 'Liptovská Štiavnica'),
  ('TJ Družstevník Belá - Dulice', 'Belá Dulice'),
  ('OŠK RENOP Liptovská Teplá', 'Liptovská Teplá'),
  ('TJ Slovan Podvysoká', 'Podvysoká'),
  ('TJ Jednota Málinec', 'Málinec'),
  ('OFK Slovenská Ľupča', 'Slovenská Ľupča'),
  ('Obecný futbalový klub Hliník nad Hronom', 'Hliník n. Hronom'),
  ('Športový klub Vinica', 'Vinica'),
  ('MFK Baník Veľký Krtíš', 'Veľký Krtíš'),
  ('ŠK Partizán Čierny Balog', 'Partizán Č. Balog'),
  ('FK Jesenské', 'Jesenské'),
  ('OFK Olováry', 'Olováry'),
  ('TJ Družstevník Látky', 'Látky'),
  ('OŠK Radzovce', 'Radzovce'),
  ('MFK Detva', 'Detva'),
  ('TJ Slovan Tomášovce', 'Tomášovce'),
  ('FK Iskra Hnúšťa', 'Hnúšťa'),
  ('Telovýchovná jednota Lovča', 'Lovča'),
  ('TJ Slovan Dudince', 'Dudince'),
  ('TJ Družstevník Bitarová', 'Bitarová'),
  ('OŠK Nededza', 'Nededza'),
  ('FK Fatran Varín', 'Varín'),
  ('OŠK Kamenná Poruba', 'Kamenná Poruba'),
  ('TJ Pokrok Stará Bystrica', 'Stará Bystrica'),
  ('TJ Slovan Skalité', 'Skalité'),
  ('ŠK Gbeľany', 'Gbeľany'),
  ('TJ Snaha Zborov nad Bystricou', 'Zborov'),
  ('TJ Horný Hričov', 'Horný Hričov'),
  ('TJ Kysučan Korňa', 'Korňa'),
  ('TJ SPARTAK Vysoká nad Kysucou', 'Vysoká'),
  ('ŠK Radoľa', 'Radoľa'),
  ('TJ Tatran Oravské Veselé B', 'Oravské Veselé B'),
  ('FK Slovan Trstená', 'Trstená'),
  ('TJ NOVOŤ', 'Novoť'),
  ('ŠK Olympia Bobrov', 'Bobrov'),
  ('TJ Slovan Bystrička', 'Bystrička'),
  ('Futbalový klub ATTACK Vrútky', 'Attack Vrútky'),
  ('TJ Sokol Liesek', 'Liesek'),
  ('TJ Slovan Magura Vavrečka', 'Magura Vavrečka'),
  ('FK Slovan Žabokreky', 'Žabokreky'),
  ('TJ Turčan Košťany', 'Turčan Košťany'),
  ('TJ Máj Ružomberok-Černová', 'Ružomberok Černová'),
  ('ŠK Turčianska Štiavnička', 'Turčianska Štiavnička'),
  ('TJ Roháče Zuberec', 'Roháče Zuberec'),
  ('TJ Štart Liptovský Ján', 'Liptovský Ján'),
  ('TJ Družstevník Dlhá nad Oravou', 'Dlhá'),
  ('OFK Liptovská Lúžna', 'Liptovská Lúžna'),
  ('Futbalový klub Podkonice B', 'Podkonice B'),
  ('FK Sitno Banská Štiavnica', 'Banská Štiavnica'),
  ('TJ ŠK Hronec', 'Hronec'),
  ('OFK 1950 Priechod', 'Priechod'),
  ('FK Šalková', 'Šalková'),
  ('FK 1928 Jasenie', 'Jasenie'),
  ('TJ ŠK Sokol Jakub', 'Jakub'),
  ('FK Slovan Kúpele Sliač', 'Kúpele Sliač'),
  ('ŠK SÁSOVÁ', 'Sásová'),
  ('MFK Strojár Krupina', 'Strojár Krupina'),
  ('FK 09 Bacúch', 'Bacúch'),
  ('FK - 34 Brusno - Ondrej', 'Brusno Ondrej'),
  ('TJ Tatran Čierny Balog', 'Tatran Č. Balog'),
  ('FK Sokol Braväcovo', 'Braväcovo'),
  ('AK šport Selce', 'šport Selce'),
  ('TJ Prameň Dolná Strehová', 'Dolná Strehová'),
  ('TJ Vinohrad Čebovce', 'Čebovce'),
  ('1. FK Buzitka', 'Buzitka'),
  ('MFK Jelšava', 'Jelšava'),
  ('TJ Ipeľ Balog nad Ipľom', 'Balog'),
  ('TJ Družstevník Kráľ', 'Kráľ'),
  ('FK Mesta Tornaľa', 'Tornaľa'),
  ('TJ Družstevník Sklabiná', 'Sklabiná'),
  ('MFK Revúca', 'Revúca'),
  ('TJ Slovan Halič', 'Halič'),
  ('FC 98 Hajnáčka', 'Hajnáčka'),
  ('TJ Baník Ružiná', 'Ružiná'),
  ('TJ Štart Kokava nad Rimavicou', 'Kokava'),
  ('TJ Sklotatran Poltár', 'Poltár'),
  ('Telovýchovná jednota Beskyd Svrčinovec', 'Beskyd Svrčinovec'),
  ('Športový klub Nesluša', 'Nesluša'),
  ('TJ SLOVAN KLOKOČOV', 'Klokočov'),
  ('TJ Tatran Oščadnica', 'Oščadnica'),
  ('FK VADIČOV', 'Vadičov'),
  ('FK LODNO', 'Lodno'),
  ('TJ Olešná', 'Olešná'),
  ('Športový klub Horelica', 'Horelica'),
  ('TJ Slovan Povina', 'Povina'),
  ('TJ Slovan Rudinská', 'Rudinská'),
  ('TJ Kysučan Ochodnica', 'Ochodnica'),
  ('FK Polom Raková', 'Polom Raková'),
  ('MŠK Snežnica', 'Snežnica'),
  ('TJ Slovan Nová Bystrica', 'Nová Bystrica'),
  ('RSC HAMSIK ACADEMY Banská Bystrica o.z.', 'Hamšík Academy'),
  ('ŠK Obecný podnik lesov Poniky', 'Poniky'),
  ('FK - Baník Ľubietová', 'Ľubietová'),
  ('TJ Slovan Malachov', 'Malachov'),
  ('TJ Družstevník Mičiná', 'Mičiná'),
  ('OFK Slovan Valaská', 'Valaská'),
  ('TJ Slovan Beňuš', 'Beňuš'),
  ('Jupie Banská Bystrica', 'Jupie BB'),
  ('ŠK Sokol FO Staré Hory', 'Staré Hory'),
  ('Športový klub Hrochoť', 'Hrochoť'),
  ('ŠK Zornička Riečka', 'Riečka'),
  ('TJ Slovan Tajov', 'Tajov'),
  ('FK Šalková B', 'Šalková B'),
  ('OFK 1950 Priechod B', 'Priechod B'),
  ('TJ Slovan Pohronská Polhora', 'Pohronská Polhora'),
  ('TJ Partizán Dolná Lehota', 'Dolná Lehota'),
  ('TJ Tatran Harmanec', 'Harmanec'),
  ('TJ Sokol Medzibrod B', 'Medzibrod B'),
  ('TJ Iskra Horné Pršany', 'Horné Pršany'),
  ('FK Sokol Braväcovo B', 'Braväcovo B'),
  ('ŠK Heľpa', 'Heľpa'),
  ('TJ Slovan Michalová', 'Michalová'),
  ('AK šport Selce B', 'šport Selce B'),
  ('TJ Partizán Hiadeľ', 'Hiadeľ'),
  ('TJ Dynamo Príbovce', 'Príbovce'),
  ('Tatran Turany', 'Turany'),
  ('FK Trebostovo', 'Trebostovo'),
  ('FK Valča', 'Valča'),
  ('TJ Družstevník Dubové', 'Dubové'),
  ('TJ Družstevník Belá - Dulice B', 'Belá Dulice B'),
  ('TJ ŠK Drienok Mošovce', 'Drienok Mošovce'),
  ('TJ Družstevník Ďanová', 'Ďanová'),
  ('FC Tatran Kláštor pod Znievom', 'Kláštor'),
  ('FO Tatran Sučany', 'Sučany'),
  ('TJ Družstevník Dražkovce', 'Dražkovce'),
  ('TJ Turčianske Kľačany', 'Turčianske Kľačany'),
  ('TJ Žiara Horná Štubňa', 'Horná Štubňa'),
  ('MFK Tepličan', 'Tepličan'),
  ('TJ Družstevník Slovany', 'Slovany'),
  ('TJ Družba Malý Čepčín', 'Malý Čepčín'),
  ('TJ COMPEL RAIL Lipovec', 'Rail Lipovec'),
  ('TJ Družstevník Blatnica', 'Blatnica'),
  ('TJ Družstevník Háj', 'Háj'),
  ('OŠK Lisková', 'Lisková'),
  ('OŠK Ludrová', 'Ludrová'),
  ('TJ Iľanovo', 'Iľanovo'),
  ('ŠK Lúčky - kúpele', 'Lúčky kúpele'),
  ('OŠK LIKAVKA', 'Likavka'),
  ('TJ Partizán Ľubeľa', 'Ľubeľa'),
  ('TJ Tatran Hybe', 'Hybe'),
  ('1. OFC Liptovské Sliače', 'Liptovské Sliače'),
  ('TJ Družba Smrečany - Žiar', 'Smrečany Žiar'),
  ('Futbalový klub Baník Dúbrava', 'Dúbrava'),
  ('ŠKM Liptovský Hrádok', 'Liptovský Hrádok'),
  ('ŠK Kriváň Važec', 'Kriváň Važec'),
  ('TJ Sokol Komjatná', 'Komjatná'),
  ('OFK Partizánska Ľupča', 'Partizánska Ľupča'),
  ('TJ Družstevník Liptovský Trnovec', 'Liptovský Trnovec'),
  ('ŠK TJ Iskra Hrboltová', 'Hrboltová'),
  ('ŠK Bobrovec', 'Bobrovec'),
  ('ŠK Kriváň Lipt. Ondrašová', 'Lipt. Ondrašová'),
  ('TJ Družstevník Východná', 'Východná'),
  ('TJ Družstevník Liptovská Kokava', 'Liptovská Kokava'),
  ('TJ Poľana Hubová', 'Poľana Hubová'),
  ('OFK Podtureň', 'Podtureň'),
  ('FK Liptovské Vlachy', 'Liptovské Vlachy'),
  ('TJ Prosiek', 'Prosiek'),
  ('TJ Tatran Liptovské Revúce', 'Liptovské Revúce'),
  ('ŠK Demänová', 'Demänová'),
  ('OŠK Jamník', 'Jamník'),
  ('TJ Družstevník Štiavnička', 'Štiavnička'),
  ('TJ Ďumbier Uhorská Ves', 'Uhorská Ves'),
  ('TJ Gôtovany', 'Gôtovany'),
  ('TJ Liptov Vavrišovo', 'Liptov Vavrišovo'),
  ('OŠK Svätý Kríž', 'Svätý Kríž'),
  ('TJ Liptovský Ondrej', 'Liptovský Ondrej'),
  ('Futbalisti, o.z.', 'Futbalisti'),
  ('ŠK Slovan Vidiná', 'Vidiná'),
  ('TJ "Slovan" Hrnčiarske Zalužany', 'Hrnčiarske Zalužany'),
  ('TJ Santrio Láza', 'Santrio Láza'),
  ('OŠK Biskupice', 'Biskupice'),
  ('Cinobanský športový klub', 'Cinobanský'),
  ('TJ Družstevník Mýtna', 'Mýtna'),
  ('TJ - FK Stará Halič', 'Stará Halič'),
  ('1. FK Buzitka B', 'Buzitka B'),
  ('FC Slovan Divín', 'Divín'),
  ('TJ Panické Dravce', 'Panické Dravce'),
  ('FK Iskra Hnúšťa B', 'Hnúšťa B'),
  ('FK obec Lubeník', 'obec Lubeník'),
  ('Telovýchovná jednota Družstevník Klenovec', 'Klenovec'),
  ('TJ - FK Veľký Blh', 'Veľký Blh'),
  ('MŠK Tisovec', 'Tisovec'),
  ('TJ Sokol Opatovská Nová Ves', 'Nová Ves'),
  ('TJ Slovan Modrý Kameň', 'Modrý Kameň'),
  ('TJ Inter Bátorová', 'Bátorová'),
  ('FK Záhorce', 'Záhorce'),
  ('FK Lesenice', 'Lesenice'),
  ('TJ Stredné Plachtince - OFK', 'Stredné Plachtince'),
  ('Obecný futbalový klub Dačov Lom', 'Dačov Lom'),
  ('FK Bušince', 'Bušince'),
  ('TJ Družstevník Kamenné Kosihy', 'Kamenné Kosihy'),
  ('Obecný futbalový klub Želovce', 'Želovce'),
  ('TJ Partizán Hrušov', 'Hrušov'),
  ('TJ Partizán Veľká Lehota', 'Veľká Lehota'),
  ('OŠK Hodruša - Hámre', 'Hodruša Hámre'),
  ('OŠK Lutila', 'Lutila'),
  ('TJ Družstevník Janova Lehota', 'Janova Lehota'),
  ('TJ Družstevník Lovčica - Trubín', 'Lovčica Trubín'),
  ('ŠK Rudno nad Hronom', 'Rudno'),
  ('ŠKF Kremnica', 'ŠKF Kremnica'),
  ('TJ Inter Horná Ves', 'Horná Ves'),
  ('TJ Sokol Repište', 'Repište'),
  ('Futbalový klub Hronský Beňadik', 'Hronský Beňadik'),
  ('TJ Baník Štiavnické Bane', 'Štiavnické Bane'),
  ('TJ - Prestavlky', 'Prestavlky'),
  ('OŠK Brehy', 'Brehy'),
  ('FK Žarnovica', 'Žarnovica'),
  ('FK Sokol Svätý Anton', 'Svätý Anton'),
  ('ŠK Voznica', 'Voznica'),
  ('TJ Hronská Dúbrava', 'Hronská Dúbrava'),
  ('Telovýchovná jednota Lovča B', 'Lovča B'),
  ('TJ Družstevník Pitelová', 'Pitelová'),
  ('TJ Sokol Tekovská Breznica', 'Tekovská Breznica'),
  ('TJ Tatran Bzenica', 'Bzenica'),
  ('ŠK Jastrabá', 'Jastrabá'),
  ('FK Vyhne', 'Vyhne'),
  ('TJ Sokol Trnavá Hora', 'Trnavá Hora'),
  ('ŠK Slaská', 'Slaská'),
  ('TJ Agro Ostrá Lúka', 'Ostrá Lúka'),
  ('TJ Kriváň', 'Kriváň'),
  ('TJ Sokol FO Sielnica', 'Sielnica'),
  ('TJ Detvianska Huta', 'Detvianska Huta'),
  ('MFK Spartak Hriňová', 'Hriňová'),
  ('Telovýchovná jednota Družstevník Očová', 'Očová'),
  ('OŠK Stožok', 'Stožok'),
  ('TJ Slovan AX Budča', 'AX Budča'),
  ('TJ Družstevník Hontianske Tesáre', 'Hontianske Tesáre'),
  ('TJ Družstevník Bzovík', 'Bzovík'),
  ('OTJ Hontianske Nemce', 'Hontianske Nemce'),
  ('OŠK Dobrá Niva', 'Dobrá Niva'),
  ('TJ Družstevník Senohrad', 'Senohrad'),
  ('MFK Strojár Krupina B', 'Strojár Krupina B'),
  ('OZ OFK Sebechleby', 'Sebechleby'),
  ('TJ Tatran VLM Pliešovce', 'VLM Pliešovce'),
  ('OFK Leštiny', 'Leštiny'),
  ('OŠK Hruštín', 'Hruštín'),
  ('OŠK Lokca', 'Lokca'),
  ('FK Nižná', 'Nižná'),
  ('TJ Oravan Rabča', 'Oravan Rabča'),
  ('TJ Oravská Lesná', 'Oravská Lesná'),
  ('OŠK BABÍN', 'Babín'),
  ('TJ Družstevník Vitanová', 'Vitanová'),
  ('TJ Tatran Zákamenné', 'Zákamenné'),
  ('OŠK BREZA', 'Breza'),
  ('FC TJ Oravský Podzámok', 'Oravský Podzámok'),
  ('TJ Tatran Klin', 'Klin'),
  ('OŠK Istebné', 'Istebné'),
  ('TJ Diamond Lomná', 'Diamond Lomná'),
  ('OŠK Oravská Polhora', 'Oravská Polhora'),
  ('TJ ŠK Podbiel', 'Podbiel'),
  ('OŠK SIHELNÉ', 'Sihelné'),
  ('Obecný športový klub Zábiedovo', 'Zábiedovo'),
  ('Futbalový klub Oravan Brezovica', 'Oravan Brezovica'),
  ('TJ Fatran Zázrivá', 'Zázrivá'),
  ('Futbalový klub Nižná', 'Nižná'),
  ('TJ Družstevník Oravská Poruba', 'Oravská Poruba'),
  ('TJ Tatran Chlebnice', 'Chlebnice'),
  ('OŠK Pribiš', 'Pribiš'),
  ('RSC HAMSIK ACADEMY Banská Bystrica o.z. B', 'Banská Bystrica B'),
  ('Futbalový klub Lovinobaňa', 'Lovinobaňa'),
  ('TJ Družstevník Kráľ D', 'Kráľ D'),
  ('TJ Tatran Čierny Balog B', 'Čierny Balog B'),
  ('OFK Slovenská Ľupča B', 'Slovenská Ľupča B'),
  ('TJ Agrokomplex Sklené', 'Sklené'),
  ('TJ Valaská Dubová', 'Valaská Dubová'),
  ('OŠK Uhorské', 'Uhorské'),
  ('MŠK Podrečany', 'Podrečany'),
  ('KC Hodejov', 'KC Hodejov'),
  ('"TJD Príbelce" B', 'Príbelce B'),
  ('OŠK Dobrá Niva B', 'Dobrá Niva B'),
  ('Telovýchovná jednota Tatran Oravský Biely Potok', 'Biely Potok')
  ) v(ime, kratko)
 where t.name = v.ime
   and t.country_id = (select id from public.countries where code = 'SK')
   and t.short_name is distinct from v.kratko;

update public.competitions c
   set sort_order = v.red
  from (values ('sk-ssfz-6liga-a', 4), ('sk-ssfz-6liga-b', 5), ('sk-ssfz-6liga-c', 6), ('sk-ssfz-6liga-d', 7)) v(slug, red)
 where c.slug = v.slug;
